-- ============================================================
-- FILE: sql/00_AUTO_GENERATE_CODES.sql
-- MỤC ĐÍCH: Tạo các Stored Procedure tự động sinh mã nghiệp vụ
-- CHẠY file này trong SQL Server trước khi chạy Flask
-- ============================================================

-- 1. Sinh mã hóa đơn bán: HDB0000001
IF OBJECT_ID('dbo.usp_SINH_MA_HOADON_BAN', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_SINH_MA_HOADON_BAN;
GO
CREATE PROCEDURE dbo.usp_SINH_MA_HOADON_BAN
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @so INT;
    SELECT @so = ISNULL(MAX(CAST(SUBSTRING(MAHDB, 4, LEN(MAHDB)) AS INT)), 0) + 1
    FROM HOADON_BAN;
    SELECT 'HDB' + RIGHT('0000000' + CAST(@so AS VARCHAR), 7) AS MAHDB;
END;
GO

-- 2. Sinh mã hóa đơn nhập: HDN0000001
IF OBJECT_ID('dbo.usp_SINH_MA_HOADON_NHAP', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_SINH_MA_HOADON_NHAP;
GO
CREATE PROCEDURE dbo.usp_SINH_MA_HOADON_NHAP
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @so INT;
    SELECT @so = ISNULL(MAX(CAST(SUBSTRING(MAHDN, 4, LEN(MAHDN)) AS INT)), 0) + 1
    FROM HOADON_NHAP;
    SELECT 'HDN' + RIGHT('0000000' + CAST(@so AS VARCHAR), 7) AS MAHDN;
END;
GO

-- 3. Sinh mã thanh toán: TT000001
IF OBJECT_ID('dbo.usp_SINH_MA_THANHTOAN', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_SINH_MA_THANHTOAN;
GO
CREATE PROCEDURE dbo.usp_SINH_MA_THANHTOAN
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @so INT;
    SELECT @so = ISNULL(MAX(CAST(SUBSTRING(MATT, 3, LEN(MATT)) AS INT)), 0) + 1
    FROM THANHTOAN;
    SELECT 'TT' + RIGHT('000000' + CAST(@so AS VARCHAR), 6) AS MATT;
END;
GO

-- 4. Sinh mã khách hàng: KH000001
IF OBJECT_ID('dbo.usp_SINH_MA_KHACHHANG', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_SINH_MA_KHACHHANG;
GO
CREATE PROCEDURE dbo.usp_SINH_MA_KHACHHANG
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @so INT;
    SELECT @so = ISNULL(MAX(CAST(SUBSTRING(MAKH, 3, LEN(MAKH)) AS INT)), 0) + 1
    FROM KHACHHANG;
    SELECT 'KH' + RIGHT('000000' + CAST(@so AS VARCHAR), 6) AS MAKH;
END;
GO

-- 5. Sinh mã nhà cung cấp: NCC00001
IF OBJECT_ID('dbo.usp_SINH_MA_NHACUNGCAP', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_SINH_MA_NHACUNGCAP;
GO
CREATE PROCEDURE dbo.usp_SINH_MA_NHACUNGCAP
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @so INT;
    SELECT @so = ISNULL(MAX(CAST(SUBSTRING(MA_NCC, 4, LEN(MA_NCC)) AS INT)), 0) + 1
    FROM NHACUNGCAP;
    SELECT 'NCC' + RIGHT('00000' + CAST(@so AS VARCHAR), 5) AS MA_NCC;
END;
GO

-- 6. Sinh mã sản phẩm: SP000001
IF OBJECT_ID('dbo.usp_SINH_MA_SANPHAM', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_SINH_MA_SANPHAM;
GO
CREATE PROCEDURE dbo.usp_SINH_MA_SANPHAM
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @so INT;
    SELECT @so = ISNULL(MAX(CAST(SUBSTRING(MASP, 3, LEN(MASP)) AS INT)), 0) + 1
    FROM SANPHAM;
    SELECT 'SP' + RIGHT('000000' + CAST(@so AS VARCHAR), 6) AS MASP;
END;
GO

-- 7. Sinh mã sản phẩm chi tiết: CT000001
IF OBJECT_ID('dbo.usp_SINH_MA_SANPHAM_CHITIET', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_SINH_MA_SANPHAM_CHITIET;
GO
CREATE PROCEDURE dbo.usp_SINH_MA_SANPHAM_CHITIET
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @so INT;
    SELECT @so = ISNULL(MAX(CAST(SUBSTRING(MASPCT, 3, LEN(MASPCT)) AS INT)), 0) + 1
    FROM SANPHAM_CHITIET;
    SELECT 'CT' + RIGHT('000000' + CAST(@so AS VARCHAR), 6) AS MASPCT;
END;
GO

-- 8. Sinh mã bảng giá: BG000001
IF OBJECT_ID('dbo.usp_SINH_MA_BANGGIA', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_SINH_MA_BANGGIA;
GO
CREATE PROCEDURE dbo.usp_SINH_MA_BANGGIA
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @so INT;
    SELECT @so = ISNULL(MAX(CAST(SUBSTRING(MAGIA, 3, LEN(MAGIA)) AS INT)), 0) + 1
    FROM BANGGIA;
    SELECT 'BG' + RIGHT('000000' + CAST(@so AS VARCHAR), 6) AS MAGIA;
END;
GO

-- ============================================================
-- KIỂM TRA SAU KHI TẠO:
-- EXEC dbo.usp_SINH_MA_HOADON_BAN;
-- EXEC dbo.usp_SINH_MA_HOADON_NHAP;
-- EXEC dbo.usp_SINH_MA_THANHTOAN;
-- EXEC dbo.usp_SINH_MA_KHACHHANG;
-- EXEC dbo.usp_SINH_MA_NHACUNGCAP;
-- EXEC dbo.usp_SINH_MA_SANPHAM;
-- EXEC dbo.usp_SINH_MA_SANPHAM_CHITIET;
-- EXEC dbo.usp_SINH_MA_BANGGIA;
-- ============================================================
